server:
  port: 10001

spring:
  application:
    name: springcloud-zuul-gateway


zuul:
  prefix: /xiong
  ignored-services: "*"
  routes:
    provider.serviceId: springcloud-provider
    provider.path: /provider/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:6001/eureka/,http://eureka2.com:6002/eureka/,http://eureka3.com:6003/eureka/              # 服务的注册地址
  instance:
    instance-id: gateway.com
    prefer-ip-address: true
info:
  app.name: springcloudCombine
  companyname: www.wisewater.com
  build.artifactId: $project.artfactId$
  build.version: $project.version$